### ISSUE TITLE
ocaml-variants.4.11.1+BER: there are errors in configure's option

### ISSUE THREAD

**Issue by moatom** [ocaml/opam-repository#17385]
Although `./configure -prefix %{prefix}% -cc cc -aspp cc -c` is used for compiling OCaml in some packages (e.g. [ocaml-variants.4.07.1+BER](https://github.com/ocaml/opam-repository/blob/a745d1a17e803a58672c2c239e3821e3f7c4bc36/packages/ocaml-variants/ocaml-variants.4.07.1%2BBER/opam)), it doesn't seems to work for OCaml 4.11.1.

The following is the result of `opam switch create 4.11.1+BER`.
```
<><> Gathering sources ><><><><><><><><><><><><><><><><><><><><><><><><><><>  🐫 
[ocaml-variants.4.11.1+BER] downloaded from cache at https://opam.ocaml.org/cache

<><> Processing actions <><><><><><><><><><><><><><><><><><><><><><><><><><>  🐫 
∗ installed base-bigarray.base
∗ installed base-threads.base
∗ installed base-unix.base
[ERROR] The compilation of ocaml-variants failed at "/Users/moatom/.opam/opam-init/hooks/sandbox.sh build ./configure -prefix
        /Users/moatom/.opam/4.11.1+BER -cc cc -aspp cc -c".

#=== ERROR while compiling ocaml-variants.4.11.1+BER ==========================#
# context     2.0.7 | macos/x86_64 |  | https://opam.ocaml.org#dddf7f21
# path        ~/.opam/4.11.1+BER/.opam-switch/build/ocaml-variants.4.11.1+BER
# command     ~/.opam/opam-init/hooks/sandbox.sh build ./configure -prefix /Users/moatom/.opam/4.11.1+BER -cc cc -aspp cc -c
# exit-code   1
# env-file    ~/.opam/log/ocaml-variants-2623-d8a4ae.env
# output-file ~/.opam/log/ocaml-variants-2623-d8a4ae.out
### output ###
# configure: error: unrecognized option: `-cc'
# Try `./configure --help' for more information



<><> Error report <><><><><><><><><><><><><><><><><><><><><><><><><><><><><>  🐫 
┌─ The following actions failed
│ λ build ocaml-variants 4.11.1+BER
└─ 
┌─ The following changes have been performed (the rest was aborted)
│ ∗ install base-bigarray base
│ ∗ install base-threads  base
│ ∗ install base-unix     base
└─ 
```
I haven't gotten this type of error in installing 4.04.0+BER, 4.02.1+BER, 4.07.1+BER.

I could personally avoid this error by changing `["./configure" "-prefix" "%{prefix}%" "-cc" "cc" "-aspp" "cc -c"]` in https://github.com/ocaml/opam-repository/pull/17365 to ` ["./configure" "--prefix=%{prefix}%" "CC=cc" "ASPP=cc -c"] `.

**Comment by mseri** [comment]
@moatm with an `opam upgrade` it should be fixed now. Thanks for the report

**Comment by biboudis** [comment]
Thanks for the fix @yallop!

Seems the error still exists after a clean `opam init --disable-sandboxing` fby a switch create.

It seems that we need an equals sign between the aspp and cc? 🤔 

`cc -aspp=cc -c` instead of `cc -aspp cc -c`

```
> cc --version ## on my system 
Apple clang version 12.0.0 (clang-1200.0.32.21)
Target: x86_64-apple-darwin19.6.0
```

**Comment by yallop** [comment]
I can't test this easily, but I wonder if it should be something like `-aspc='cc -c'`, i.e. passing the full command "`cc -c`" as the argument to `-aspp`.

**Comment by biboudis** [comment]
Maybe that also works but is `-aspp` supposed to include the trailing `-c` or does the latter belong to the env variable CC?

**Comment by yallop** [comment]
It's a bit of a puzzle, but the original quoted version looks like this:
```
"-cc" "cc" "-aspp" "cc -c"
```
which looks like it should be parsed like this:
```
("-cc" "cc")
("-aspp" "(cc -c)")
```

**Comment by biboudis** [comment]
Aha. So your comment above is correct! Go for it and I upgrade and test.

**Comment by biboudis** [comment]
WDYT? Should I open a PR with this?

**Comment by yallop** [comment]
If it works for you, I think you should!

**Comment by biboudis** [comment]
How can I test locally? is there any way to test it?

**Comment by yallop** [comment]
If you have a local clone of `opam-repository` you can use that instead of the remote repository, something like this:

```
opam remote set-url default /path/to/local/clone
```

after which all `opam` commands should use the local copy.

**Comment by moatom** [comment]
@biboudis 
Cool! It seems I forgot to test @mseri and @yallop's fix.
It doesn't work for me, too.
```
~ ❯❯❯ opam switch create bern111test 4.11.1+BER                                                                                                                                                        ✘ 2

<><> Gathering sources ><><><><><><><><><><><><><><><><><><><><><><><><><><>  🐫
[ocaml-variants.4.11.1+BER] found in cache

<><> Processing actions <><><><><><><><><><><><><><><><><><><><><><><><><><>  🐫
∗ installed base-bigarray.base
∗ installed base-threads.base
∗ installed base-unix.base
[ERROR] The compilation of ocaml-variants failed at "/Users/moatom/.opam/opam-init/hooks/sandbox.sh build ./configure -prefix /Users/moatom/.opam/bern111test CC=cc -aspp cc -c".

#=== ERROR while compiling ocaml-variants.4.11.1+BER ==========================#
# context     2.0.7 | macos/x86_64 |  | https://opam.ocaml.org#eb70a9b0
# path        ~/.opam/bern111test/.opam-switch/build/ocaml-variants.4.11.1+BER
# command     ~/.opam/opam-init/hooks/sandbox.sh build ./configure -prefix /Users/moatom/.opam/bern111test CC=cc -aspp cc -c
# exit-code   1
# env-file    ~/.opam/log/ocaml-variants-71301-1872ec.env
# output-file ~/.opam/log/ocaml-variants-71301-1872ec.out
### output ###
# configure: error: unrecognized option: `-aspp'
# Try `./configure --help' for more information



<><> Error report <><><><><><><><><><><><><><><><><><><><><><><><><><><><><>  🐫
┌─ The following actions failed
│ λ build ocaml-variants 4.11.1+BER
└─
┌─ The following changes have been performed (the rest was aborted)
│ ∗ install base-bigarray base
│ ∗ install base-threads  base
│ ∗ install base-unix     base
└─

<><> ocaml-variants.4.11.1+BER troubleshooting ><><><><><><><><><><><><><><>  🐫
=> A failure in the middle of the build may be caused by build parallelism
      (enabled by default).
      Please file a bug report at https://github.com/ocaml/ocaml/issues
=> You can try installing again including --jobs=1
      to force a sequential build instead.
# Run eval $(opam env) to update the current shell environment
Switch initialisation failed: clean up? ('n' will leave the switch partially installed) [Y/n] Y
```

Anyway, as to my research of the configure file, my and your fix is correct.
- new: https://github.com/ocaml/ocaml/blob/trunk/configure#L16504
- old: https://github.com/ocaml/ocaml/blob/881ec04f39128569be1661b9c07b1410fcca6e37/configure#L119

**Comment by biboudis** [comment]
Thx for the confirmation @moatom!!
