### ISSUE TITLE
capnproto failing on 32bit x86 because of some constraints (conf-capnproto)

### ISSUE THREAD

**Issue by moyodiallo** [ocaml/opam-repository#24639]
This issue is reported here https://github.com/mirage/capnp-rpc/issues/273, there's also a PR opened to fix it https://github.com/capnproto/capnproto/pull/1824.

The issue appears on 32bit x86 machine when you are dealing with a file or directory having an inode number that exceeds 32 bits. Or the size of the file exceeds 4G bytes. On a normal use case, it's rare to have those constraints but not on some servers where most of the time dealing with a lot of files (inode exceeding 32bit) and some files exceeding 4G bytes.

cc: @tmcgilchrist

**Comment by moyodiallo** [comment]
The original issue was fixed https://github.com/capnproto/capnproto/pull/1830.

This issue don't affect a regular user, so could be closed.

**Comment by shonfeder** [comment]
This is actually still an issue on debian-12, which, due to the version freeze policy on the stable debian repo, hasn't picked up the fixes on later versions. See https://github.com/ocurrent/ocaml-ci/issues/931.
