### ISSUE TITLE
Jane st. base packaging bug (requirements)

### ISSUE THREAD

**Issue by yami-no-ryuu** [ocaml/opam-repository#25829]
Jane st. **base** is uninstallable atm.
Looks like the requirements stanza is incorrect.
`opam info base.v0.17.0`
```
depends      "ocaml" {>= "5.1.0"}
             "ocaml_intrinsics_kernel"
             "sexplib0" {>= "v0.17" & < "0.18"}
```
Should be "v0.18".

**Comment by dbuenzli** [comment]
Did you `opam update` ? This should have been fixed by https://github.com/ocaml/opam-repository/pull/25798

**Comment by edwintorok** [comment]
Same issue here, running `opam update` doesn't fix it.
https://opam.ocaml.org/index.tar.gz  still contains this line (maybe it takes a while to update from git?):
```
  "sexplib0"                {>= "v0.17" & < "0.18"}
```

**Comment by dbuenzli** [comment]
It certainly takes a while, but maybe not 3 days… If I do `opam update && opam config report` it says default repo at https://github.com/ocaml/opam-repository/commit/2b6e600e5b1d71ecc8ddcc390312fdfca6c80615 so something seems broken in the sync infra.

**Comment by dbuenzli** [comment]
Ping @mseri and @raphael-proust (whose contact I found on the wiki), the repo has been stuck for quite a while now.

**Comment by mseri** [comment]
This should have been fixed by https://github.com/ocaml/opam-repository/pull/25798
I have opened an issue on the ocaml infrastructure repo

Sorry for the wait, I was on holiday until this morning

**Comment by dbuenzli** [comment]
After an `opam update` it seems this is now corrected:

```
> opam info --raw base.v0.17.0  | grep sexplib0
  "sexplib0" {>= "v0.17" & < "v0.18"}
```
