### ISSUE TITLE
opam fails to install ocaml-top

### ISSUE THREAD

**Issue by fredOnGitHub** [ocaml/opam-repository#9773]
Mac version 10.12.5
Hello fail to install
zarith
ocaml-top
----------------------------------------------------------------------------
i was said at https://github.com/ocaml/opam/issues/2992
...Regarding the ocaml-top error please follow the advice given in the error message:

=-=- conf-gtksourceview.2 troubleshooting -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
=> This package requires gtksourceview 2.0 development packages installed on your system
=> On OSX, install the gtksourceview' andlibxml2' packages and define PKG_CONFIG_PATH:

export PKG_CONFIG_PATH=/usr/X11/lib/pkgconfig/:/usr/local/lib/pkgconfig:/usr/local/opt/libxml2/lib/pkgconfig/
-------------------
OK I have tried
```
Opam install gtksourceview
[ERROR] No package named gtksourceview found.

opam list -a | grep -i "GtkSourceView"
conf-gtksourceview                            --  Virtual package relying on a G

******************$ sudo Opam install conf-gtksourceview
Password:
[WARNING] Running as root is not recommended
The following actions will be performed:
∗  install conf-gtksourceview 2

=-=- Gathering sources =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

=-=- Processing actions -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
[ERROR] The compilation of conf-gtksourceview failed at "pkg-config --short-errors --print-errors gtksourceview-2.0".

#=== ERROR while installing conf-gtksourceview.2 ==============================#
# opam-version 1.2.2
# os           darwin
# command      pkg-config --short-errors --print-errors gtksourceview-2.0
# path         /Users/****/.opam/system/build/conf-gtksourceview.2
# compiler     system (4.04.2)
# exit-code    127
# env-file     /Users/****/.opam/system/build/conf-gtksourceview.2/conf-gtksourceview-800-7afd23.env
# stdout-file  /Users/****/.opam/system/build/conf-gtksourceview.2/conf-gtksourceview-800-7afd23.out
# stderr-file  /Users/****/.opam/system/build/conf-gtksourceview.2/conf-gtksourceview-800-7afd23.err

=-=- Error report -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
The following actions failed
∗  install conf-gtksourceview 2
No changes have been performed

=-=- conf-gtksourceview.2 troubleshooting -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
=> This package requires gtksourceview 2.0 development packages installed on your system
=> On OSX, install the `gtksourceview' and `libxml2' packages and define PKG_CONFIG_PATH:

export PKG_CONFIG_PATH=/usr/X11/lib/pkgconfig/:/usr/local/lib/pkgconfig:/usr/local/opt/libxml2/lib/pkgconfig/

----------------------------------------------------------------------------

Before

i ihave done

brew install opam
opam init
opam install zarith
opam install ocaml-top

Here the report

Somebody knows the issue ?

Thanks

*******:ocaml ****$ opam init
Checking for available remotes: rsync and local, git.

you won't be able to use mercurial repositories unless you install the hg command on your system.
you won't be able to use darcs repositories unless you install the darcs command on your system.

=-=- Fetching repository information =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
[default] synchronized from https://opam.ocaml.org

=-=- Gathering sources =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

=-=- Processing actions -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
∗ installed base-bigarray.base
∗ installed base-threads.base
∗ installed base-unix.base
Done.

In normal operation, OPAM only alters files within ~/.opam.

During this initialisation, you can allow OPAM to add information to two
other files for best results. You can also make these additions manually
if you wish.

If you agree, OPAM will modify:

~/.bash_profile (or a file you specify) to set the right environment
variables and to load the auto-completion scripts for your shell (bash)
on startup. Specifically, it checks for and appends the following line:

. /Users/****/.opam/opam-init/init.sh > /dev/null 2> /dev/null || true

~/.ocamlinit to ensure that non-system installations of ocamlfind
(i.e. those installed by OPAM) will work correctly when running the
OCaml toplevel. It does this by adding $OCAML_TOPLEVEL_PATH to the list
of include directories.

If you choose to not configure your system now, you can either configure
OPAM manually (instructions will be displayed) or launch the automatic setup
later by running:

opam config setup -a

Do you want OPAM to modify ~/.bash_profile and ~/.ocamlinit?
(default is 'no', use 'f' to name a file other than ~/.bash_profile)
[N/y/f]

Global configuration:
Updating ~/.opam/opam-init/init.sh
Updating ~/.opam/opam-init/init.zsh
Updating ~/.opam/opam-init/init.csh
Updating ~/.opam/opam-init/init.fish

=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

To configure OPAM in the current shell session, you need to run:

eval opam config env

To correctly configure OPAM for subsequent use, add the following
line to your profile file (for instance ~/.bash_profile):

. /Users/****/.opam/opam-init/init.sh > /dev/null 2> /dev/null || true

To avoid issues related to non-system installations of ocamlfind
add the following lines to ~/.ocamlinit (create it if necessary):

let () =
try Topdirs.dir_directory (Sys.getenv "OCAML_TOPLEVEL_PATH")
with Not_found -> ()
;;

=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

*******:ocaml ****$ opam --version
1.2.2
*******:ocaml ****$ opam install zarith
The following actions will be performed:
∗ install conf-perl 1 [required by zarith]
∗ install conf-m4 1 [required by ocamlfind]
∗ install conf-gmp 1 [required by zarith]
∗ install ocamlfind 1.7.3 [required by zarith]
∗ install zarith 1.5
===== ∗ 5 =====
Do you want to continue ? [Y/n] y

=-=- Gathering sources =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
[default] https://opam.ocaml.org/archives/zarith.1.5+opam.tar.gz downloaded
[default] https://opam.ocaml.org/archives/ocamlfind.1.7.3+opam.tar.gz downloaded

=-=- Processing actions -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
∗ installed conf-perl.1
[ERROR] The compilation of conf-gmp failed at "sh -exc cc -c $CFLAGS -I/usr/local/include test.c".
∗ installed conf-m4.1
∗ installed ocamlfind.1.7.3

#=== ERROR while installing conf-gmp.1 ========================================#
opam-version 1.2.2
os darwin
command sh -exc cc -c $CFLAGS -I/usr/local/include test.c
path /Users/****/.opam/system/build/conf-gmp.1
compiler system (4.04.2)
exit-code 1
env-file /Users/****/.opam/system/build/conf-gmp.1/conf-gmp-3884-d2d111.env
stdout-file /Users/****/.opam/system/build/conf-gmp.1/conf-gmp-3884-d2d111.out
stderr-file /Users/****/.opam/system/build/conf-gmp.1/conf-gmp-3884-d2d111.err
stderr
+ cc -c -I/usr/local/include test.c
test.c:1:10: fatal error: 'gmp.h' file not found
#include <gmp.h>
^
1 error generated.

=-=- Error report -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
The following actions were aborted
∗ install zarith 1.5
The following actions failed
∗ install conf-gmp 1
The following changes have been performed
∗ install conf-m4 1
∗ install conf-perl 1
∗ install ocamlfind 1.7.3

=-=- conf-gmp.1 troobleshooting -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
=> This package relies on external (system) dependencies that may be missing. `opam depext conf-gmp.1' may help you find the correct installation for your system.

The former state can be restored with:
opam switch import "~/.opam/system/backup/state-20170604184735.export"

Last login: Wed Jul 5 11:29:19 on ttys000
*******:~ ****$ opam install ocaml-top
The following actions will be performed:
∗ install conf-gtksourceview 2 [required by ocaml-top]
∗ install ocp-build 1.99.19-beta [required by ocaml-top]
∗ install result 1.2 [required by cmdliner]
∗ install base-bytes base [required by re]
∗ install ocamlbuild 0.11.0 [required by cmdliner, re]
∗ install lablgtk 2.18.5 [required by ocaml-top]
∗ install topkg 0.9.0 [required by cmdliner]
∗ install re 1.7.1 [required by ocp-index]
∗ install cmdliner 1.0.0 [required by ocp-indent, ocp-index]
∗ install ocp-indent 1.6.0 [required by ocaml-top]
∗ install ocp-index 1.1.5 [required by ocaml-top]
For ocp-browser, please also install package lambda-term
∗ install ocaml-top 1.1.3
===== ∗ 12 =====
Do you want to continue ? [Y/n] y

=-=- Gathering sources =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

[default] https://opam.ocaml.org/archives/cmdliner.1.0.0+opam.tar.gz downloaded
[default] https://opam.ocaml.org/archives/ocaml-top.1.1.3+opam.tar.gz downloaded
[default] https://opam.ocaml.org/archives/ocamlbuild.0.11.0+opam.tar.gz downloaded
[default] https://opam.ocaml.org/archives/ocp-build.1.99.19-beta+opam.tar.gz downloaded
Processing 9/12: [lablgtk: from default] [ocp-indent: from default] [ocp-index: from default[default] https://opam.ocaml.org/archives/ocp-indent.1.6.0+opam.tar.gz downloaded
[default] https://opam.ocaml.org/archives/lablgtk.2.18.5+opam.tar.gz downloaded
[default] https://opam.ocaml.org/archives/result.1.2+opam.tar.gz downloaded
[default] https://opam.ocaml.org/archives/re.1.7.1+opam.tar.gz downloaded
[default] https://opam.ocaml.org/archives/topkg.0.9.0+opam.tar.gz downloaded
[default] https://opam.ocaml.org/archives/ocp-index.1.1.5+opam.tar.gz downloaded

=-=- Processing actions -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
∗ installed base-bytes.base
[ERROR] The compilation of conf-gtksourceview failed at "pkg-config --short-errors --print-errors gtksourceview-2.0".
∗ installed result.1.2
∗ installed ocamlbuild.0.11.0
∗ installed topkg.0.9.0
∗ installed cmdliner.1.0.0
∗ installed re.1.7.1
∗ installed ocp-build.1.99.19-beta
∗ installed ocp-indent.1.6.0
∗ installed ocp-index.1.1.5

#=== ERROR while installing conf-gtksourceview.2 ==============================#
opam-version 1.2.2
os darwin
command pkg-config --short-errors --print-errors gtksourceview-2.0
path /Users/****/.opam/system/build/conf-gtksourceview.2
compiler system (4.04.2)
exit-code 127
env-file /Users/****/.opam/system/build/conf-gtksourceview.2/conf-gtksourceview-615-48c407.env
stdout-file /Users/****/.opam/system/build/conf-gtksourceview.2/conf-gtksourceview-615-48c407.out
stderr-file /Users/****/.opam/system/build/conf-gtksourceview.2/conf-gtksourceview-615-48c407.err

=-=- Error report -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
The following actions were aborted
∗ install lablgtk 2.18.5
∗ install ocaml-top 1.1.3
The following actions failed
∗ install conf-gtksourceview 2
The following changes have been performed
∗ install base-bytes base
∗ install cmdliner 1.0.0
∗ install ocamlbuild 0.11.0
∗ install ocp-build 1.99.19-beta
∗ install ocp-indent 1.6.0
∗ install ocp-index 1.1.5
∗ install re 1.7.1
∗ install result 1.2
∗ install topkg 0.9.0

=-=- ocp-indent.1.6.0 installed successfully =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
=> This package requires additional configuration for use in editors. Install package 'user-setup', or manually:

for Emacs, add these lines to ~/.emacs:
(add-to-list 'load-path "/Users/****/.opam/system/share/emacs/site-lisp")
(require 'ocp-indent)

for Vim, add this line to ~/.vimrc:
set rtp^="/Users/****/.opam/system/share/ocp-indent/vim"

=-=- ocp-index.1.1.5 installed successfully -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
=> This package requires additional configuration for use in editors. Either install package 'user-setup', or manually:

for Emacs, add these lines to ~/.emacs:
(add-to-list 'load-path "/Users/****/.opam/system/share/emacs/site-lisp")
(require 'ocp-index)

for Vim, add the following line to ~/.vimrc:
set rtp+=/Users/****/.opam/system/share/ocp-index/vim

=-=- conf-gtksourceview.2 troubleshooting -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
=> This package requires gtksourceview 2.0 development packages installed on your system
=> On OSX, install the gtksourceview' andlibxml2' packages and define PKG_CONFIG_PATH:

export PKG_CONFIG_PATH=/usr/X11/lib/pkgconfig/:/usr/local/lib/pkgconfig:/usr/local/opt/libxml2/lib/pkgconfig/

The former state can be restored with:
opam switch import "~/.opam/system/backup/state-20170605100428.export"
```

**Comment by dbuenzli** [comment]
Why do you `sudo` ? Don't do this. If opam created files with root permissions in `.opam` you may now have to change them back to your user with `chown `

Note that is seems that there are problems with `ocaml-top` but those are not the one you report (see here https://github.com/ocaml/opam-repository/pull/9738). Once these issues are fixed you should be able to install `ocaml-top` simply via the following instructions:

```
opam depext ocaml-top
opam install ocaml-top
```

But for now I'm sorry but you will have to wait for the package maintainer @altgr to fix the package.

**Comment by avsm** [comment]
fixed in #9785

**Comment by dbuenzli** [comment]
@fredOnGitHub, don't forget to `opam update` before trying again and feel free to report an issue you may be getting into in this issue.

**Comment by fredOnGitHub** [comment]
Hello,

I am sorry for all but the problem persiste.

I have done :

brew remove --force --ignore-dependencies $(brew list)
brew install opam
opam init
eval `opam config env`
opam install ocaml-top
opam update
opam install ocaml-top






I have uninstall everything 

Last login: Mon Jul 17 19:02:53 on ttys000
******************:pgm ******$ brew remove --force --ignore-dependencies $(brew list)
Uninstalling aspcud... (10 files, 460.7KB)
Uninstalling camlp4... (165 files, 143.1MB)
Uninstalling clasp... (6 files, 1.2MB)
Uninstalling gringo... (7 files, 5.5MB)
Uninstalling ocaml... (1,989 files, 206.7MB)
Uninstalling ocamlbuild... (28 files, 7MB)
Uninstalling opam... (31 files, 16.3MB)

******************:pgm ******$ brew list

******************:pgm ******$ brew install opam
==> Installing dependencies for opam: ocaml, ocamlbuild, camlp4, gringo, clasp, aspcud
==> Installing opam dependency: ocaml
==> Downloading https://homebrew.bintray.com/bottles/ocaml-4.05.0.sierra.bottle.tar.gz
Already downloaded: /Users/******/Library/Caches/Homebrew/ocaml-4.05.0.sierra.bottle.tar.gz
==> Pouring ocaml-4.05.0.sierra.bottle.tar.gz
==> Using the sandbox
🍺  /usr/local/Cellar/ocaml/4.05.0: 1,989 files, 206.7MB
==> Installing opam dependency: ocamlbuild
==> Downloading https://homebrew.bintray.com/bottles/ocamlbuild-0.11.0_2.sierra.bottle.tar.gz
Already downloaded: /Users/******/Library/Caches/Homebrew/ocamlbuild-0.11.0_2.sierra.bottle.tar.gz
==> Pouring ocamlbuild-0.11.0_2.sierra.bottle.tar.gz
🍺  /usr/local/Cellar/ocamlbuild/0.11.0_2: 28 files, 7MB
==> Installing opam dependency: camlp4
==> Downloading https://homebrew.bintray.com/bottles/camlp4-4.05+1.sierra.bottle.tar.gz
Already downloaded: /Users/******/Library/Caches/Homebrew/camlp4-4.05+1.sierra.bottle.tar.gz
==> Pouring camlp4-4.05+1.sierra.bottle.tar.gz
🍺  /usr/local/Cellar/camlp4/4.05+1: 165 files, 143.1MB
==> Installing opam dependency: gringo
==> Downloading https://homebrew.bintray.com/bottles/gringo-4.5.4.sierra.bottle.tar.gz
Already downloaded: /Users/******/Library/Caches/Homebrew/gringo-4.5.4.sierra.bottle.tar.gz
==> Pouring gringo-4.5.4.sierra.bottle.tar.gz
🍺  /usr/local/Cellar/gringo/4.5.4: 7 files, 5.5MB
==> Installing opam dependency: clasp
==> Downloading https://homebrew.bintray.com/bottles/clasp-3.2.0.sierra.bottle.tar.gz
Already downloaded: /Users/******/Library/Caches/Homebrew/clasp-3.2.0.sierra.bottle.tar.gz
==> Pouring clasp-3.2.0.sierra.bottle.tar.gz
🍺  /usr/local/Cellar/clasp/3.2.0: 6 files, 1.2MB
==> Installing opam dependency: aspcud
==> Downloading https://homebrew.bintray.com/bottles/aspcud-1.9.1.sierra.bottle.2.tar.gz
Already downloaded: /Users/******/Library/Caches/Homebrew/aspcud-1.9.1.sierra.bottle.2.tar.gz
==> Pouring aspcud-1.9.1.sierra.bottle.2.tar.gz
🍺  /usr/local/Cellar/aspcud/1.9.1: 10 files, 460.6KB
==> Installing opam
==> Downloading https://homebrew.bintray.com/bottles/opam-1.2.2_3.sierra.bottle.tar.gz
Already downloaded: /Users/******/Library/Caches/Homebrew/opam-1.2.2_3.sierra.bottle.tar.gz
==> Pouring opam-1.2.2_3.sierra.bottle.tar.gz
==> Caveats
OPAM uses ~/.opam by default for its package database, so you need to
initialize it first by running (as a normal user):

$  opam init

Run the following to initialize your environment variables:

$  eval `opam config env`

To export the needed variables every time, add them to your dotfiles.
  * On Bash, add them to `~/.bash_profile`.
  * On Zsh, add them to `~/.zprofile` or `~/.zshrc` instead.

Documentation and tutorials are available at https://opam.ocaml.org, or
via "man opam" and "opam --help".

Bash completion has been installed to:
  /usr/local/etc/bash_completion.d

zsh completions have been installed to:
  /usr/local/share/zsh/site-functions
==> Summary
🍺  /usr/local/Cellar/opam/1.2.2_3: 31 files, 16.3MB









Last login: Mon Jul 17 19:05:37 on ttys002
******************:pgm ******$ opam init
Checking for available remotes: rsync and local, git.
  - you won't be able to use mercurial repositories unless you install the hg command on your system.
  - you won't be able to use darcs repositories unless you install the darcs command on your system.


=-=- Fetching repository information =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
[default] synchronized from https://opam.ocaml.org

=-=- Gathering sources =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

=-=- Processing actions -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
∗  installed base-bigarray.base
∗  installed base-threads.base
∗  installed base-unix.base
Done.

In normal operation, OPAM only alters files within ~/.opam.

During this initialisation, you can allow OPAM to add information to two
other files for best results. You can also make these additions manually
if you wish.

If you agree, OPAM will modify:

  - ~/.bash_profile (or a file you specify) to set the right environment
    variables and to load the auto-completion scripts for your shell (bash)
    on startup. Specifically, it checks for and appends the following line:

    . /Users/******/.opam/opam-init/init.sh > /dev/null 2> /dev/null || true


  - ~/.ocamlinit to ensure that non-system installations of `ocamlfind`
    (i.e. those installed by OPAM) will work correctly when running the
    OCaml toplevel. It does this by adding $OCAML_TOPLEVEL_PATH to the list
    of include directories.

If you choose to not configure your system now, you can either configure
OPAM manually (instructions will be displayed) or launch the automatic setup
later by running:

   opam config setup -a


Do you want OPAM to modify ~/.bash_profile and ~/.ocamlinit?
(default is 'no', use 'f' to name a file other than ~/.bash_profile)
    [N/y/f] y

User configuration:
  ~/.ocamlinit is already up-to-date.
  ~/.bash_profile is already up-to-date.
Global configuration:
  Updating ~/.opam/opam-init/init.sh
  Updating ~/.opam/opam-init/init.zsh
  Updating ~/.opam/opam-init/init.csh
  Updating ~/.opam/opam-init/init.fish
# To setup the new switch in the current shell, you need to run:
eval `opam config env`










Last login: Mon Jul 17 19:10:06 on ttys000
******************:pgm ******$ eval `opam config env`
******************:pgm ******$ 







Last login: Mon Jul 17 19:20:21 on ttys005
******************:~ ******$ opam install ocaml-top
The following actions will be performed:
  ∗  install conf-gtksourceview 2             [required by ocaml-top]
  ∗  install conf-m4            1             [required by ocamlfind]
  ∗  install result             1.2           [required by cmdliner]
  ∗  install ocamlbuild         0.11.0        [required by cmdliner, re]
  ∗  install ocamlfind          1.7.3         [required by jbuilder, lablgtk]
  ∗  install topkg              0.9.0         [required by cmdliner]
  ∗  install ocp-build          1.99.19-beta  [required by ocp-index, ocp-indent, ocp-pp]
  ∗  install lablgtk            2.18.5        [required by ocaml-top]
  ∗  install jbuilder           1.0+beta10    [required by ocaml-top]
  ∗  install base-bytes         base          [required by re]
  ∗  install cmdliner           1.0.0         [required by ocp-indent, ocp-index]
  ∗  install ocp-pp             1.99.19-beta  [required by ocaml-top]
  ∗  install re                 1.7.1         [required by ocp-index]
  ∗  install ocp-indent         1.6.0         [required by ocaml-top]
  ∗  install ocp-index          1.1.5         [required by ocaml-top]
       For ocp-browser, please also install package lambda-term
  ∗  install ocaml-top          1.1.4       
===== ∗  16 =====
Do you want to continue ? [Y/n] y

=-=- Gathering sources =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  🐫 
Processing  6/16: [cmdliner: from default] [jbuilder: from default] [lablgtk: from default]
[default] https://opam.ocaml.org/archives/cmdliner.1.0.0+opam.tar.gz downloaded
[default] https://opam.ocaml.org/archives/jbuilder.1.0+beta10+opam.tar.gz downloaded
[default] https://opam.ocaml.org/archives/lablgtk.2.18.5+opam.tar.gz downloaded
[default] https://opam.ocaml.org/archives/ocamlbuild.0.11.0+opam.tar.gz downloaded
[default] https://opam.ocaml.org/archives/ocaml-top.1.1.4+opam.tar.gz downloaded
[default] https://opam.ocaml.org/archives/ocamlfind.1.7.3+opam.tar.gz downloaded
[default] https://opam.ocaml.org/archives/ocp-indent.1.6.0+opam.tar.gz downloaded
[default] https://opam.ocaml.org/archives/ocp-build.1.99.19-beta+opam.tar.gz downloaded
[default] https://opam.ocaml.org/archives/re.1.7.1+opam.tar.gz downloaded
[default] https://opam.ocaml.org/archives/result.1.2+opam.tar.gz downloaded
[default] https://opam.ocaml.org/archives/ocp-index.1.1.5+opam.tar.gz downloaded
[default] https://opam.ocaml.org/archives/topkg.0.9.0+opam.tar.gz downloaded

=-=- Processing actions -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  🐫 
[ERROR] The compilation of conf-gtksourceview failed at "pkg-config --short-errors --print-errors gtksourceview-2.0".
∗  installed conf-m4.1
∗  installed result.1.2
∗  installed ocamlfind.1.7.3
∗  installed base-bytes.base
∗  installed ocamlbuild.0.11.0
∗  installed jbuilder.1.0+beta10
∗  installed topkg.0.9.0
∗  installed cmdliner.1.0.0
∗  installed re.1.7.1
∗  installed ocp-build.1.99.19-beta
∗  installed ocp-pp.1.99.19-beta
∗  installed ocp-indent.1.6.0
∗  installed ocp-index.1.1.5

#=== ERROR while installing conf-gtksourceview.2 ==============================#
# opam-version 1.2.2
# os           darwin
# command      pkg-config --short-errors --print-errors gtksourceview-2.0
# path         /Users/******/.opam/system/build/conf-gtksourceview.2
# compiler     system (4.05.0)
# exit-code    127
# env-file     /Users/******/.opam/system/build/conf-gtksourceview.2/conf-gtksourceview-13184-d6d332.env
# stdout-file  /Users/******/.opam/system/build/conf-gtksourceview.2/conf-gtksourceview-13184-d6d332.out
# stderr-file  /Users/******/.opam/system/build/conf-gtksourceview.2/conf-gtksourceview-13184-d6d332.err



=-=- Error report -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  🐫 
The following actions were aborted
  ∗  install lablgtk   2.18.5
  ∗  install ocaml-top 1.1.4 
The following actions failed
  ∗  install conf-gtksourceview 2
The following changes have been performed
  ∗  install base-bytes base        
  ∗  install cmdliner   1.0.0       
  ∗  install conf-m4    1           
  ∗  install jbuilder   1.0+beta10  
  ∗  install ocamlbuild 0.11.0      
  ∗  install ocamlfind  1.7.3       
  ∗  install ocp-build  1.99.19-beta
  ∗  install ocp-indent 1.6.0       
  ∗  install ocp-index  1.1.5       
  ∗  install ocp-pp     1.99.19-beta
  ∗  install re         1.7.1       
  ∗  install result     1.2         
  ∗  install topkg      0.9.0       

=-=- ocp-indent.1.6.0 installed successfully =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  🐫 
=> This package requires additional configuration for use in editors. Install package 'user-setup', or manually:

   * for Emacs, add these lines to ~/.emacs:
     (add-to-list 'load-path "/Users/******/.opam/system/share/emacs/site-lisp")
     (require 'ocp-indent)

   * for Vim, add this line to ~/.vimrc:
     set rtp^="/Users/******/.opam/system/share/ocp-indent/vim"

=-=- ocp-index.1.1.5 installed successfully -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  🐫 
=> This package requires additional configuration for use in editors. Either install package 'user-setup', or manually:

   * for Emacs, add these lines to ~/.emacs:
     (add-to-list 'load-path "/Users/******/.opam/system/share/emacs/site-lisp")
     (require 'ocp-index)

   * for Vim, add the following line to ~/.vimrc:
     set rtp+=/Users/******/.opam/system/share/ocp-index/vim

=-=- conf-gtksourceview.2 troobleshooting -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  🐫 
=> This package relies on external (system) dependencies that may be missing. `opam depext conf-gtksourceview.2' may help you find the correct installation for your system.

The former state can be restored with:
    opam switch import "~/.opam/system/backup/state-20170617181612.export"


















 opam updateLast login: Mon Jul 17 20:18:55 on ttys000
******:~ ******$  opam update

=-=- Updating package repositories =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  🐫 
[default] synchronized from https://opam.ocaml.org
******:~ ******$ opam install ocaml-top
The following actions will be performed:
  ∗  install conf-gtksourceview 2             [required by ocaml-top]
  ∗  install lablgtk            2.18.5        [required by ocaml-top]
  ∗  install ocaml-top          1.1.4 
===== ∗  3 =====
Do you want to continue ? [Y/n] y

=-=- Gathering sources =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  🐫 
[lablgtk] Archive in cache
[ocaml-top] Archive in cache

=-=- Processing actions -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  🐫 
[ERROR] The compilation of conf-gtksourceview failed at "pkg-config --short-errors --print-errors gtksourceview-2.0".

#=== ERROR while installing conf-gtksourceview.2 ==============================#
# opam-version 1.2.2
# os           darwin
# command      pkg-config --short-errors --print-errors gtksourceview-2.0
# path         /Users/******/.opam/system/build/conf-gtksourceview.2
# compiler     system (4.05.0)
# exit-code    127
# env-file     /Users/******/.opam/system/build/conf-gtksourceview.2/conf-gtksourceview-19901-ffb3fd.env
# stdout-file  /Users/******/.opam/system/build/conf-gtksourceview.2/conf-gtksourceview-19901-ffb3fd.out
# stderr-file  /Users/******/.opam/system/build/conf-gtksourceview.2/conf-gtksourceview-19901-ffb3fd.err



=-=- Error report -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  🐫 
The following actions were aborted
  ∗  install lablgtk   2.18.5
  ∗  install ocaml-top 1.1.4 
The following actions failed
  ∗  install conf-gtksourceview 2
No changes have been performed

=-=- conf-gtksourceview.2 troobleshooting -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  🐫 
=> This package relies on external (system) dependencies that may be missing. `opam depext conf-gtksourceview.2' may help you find the correct installation for your system.

**Comment by dbuenzli** [comment]
I can't see an invocation of in your transcript of what I mentioned: 

```
opam depext ocaml-top
```

Note that the error message actually tells you to do this:

> => This package relies on external (system) dependencies that may be missing. `opam depext conf-gtksourceview.2' may help you find the correct installation for your system.

(I advise you to use `opam depext ocaml-top` as it is easier to type)

**Comment by fredOnGitHub** [comment]
OUAOU !

That's ok with 👍 
opam depext ocaml-top
opam install ocaml-top
ocaml-top

Thank You

and i see the split window application ocaml-top with
ocaml-top

Last login: Mon Jul 17 20:53:23 on ttys001
***************:~ ***************$ opam depext ocaml-top
OPAM plugin depext is not installed. Install it on the current switch? [Y/n] y

The following actions will be performed:
  ∗  install depext 1.0.4

=-=- Gathering sources =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  🐫 
[default] https://opam.ocaml.org/archives/depext.1.0.4+opam.tar.gz downloaded

=-=- Processing actions -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  🐫 
∗  installed depext.1.0.4
Done.

=-=- Carrying on to "opam depext ocaml-top" -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  🐫 

# Detecting depexts using flags: x86_64 osx homebrew
# The following system packages are needed:
#  - expat
#  - gtk
#  - gtksourceview
#  - libxml2
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
==> Updated Formulae
apache-geode

==> Downloading https://homebrew.bintray.com/bottles/expat-2.2.2.sierra.bottle.tar.gz
######################################################################## 100,0%
==> Pouring expat-2.2.2.sierra.bottle.tar.gz
==> Using the sandbox
==> Caveats
This formula is keg-only, which means it was not symlinked into /usr/local,
because macOS includes Expat 1.5.

If you need to have this software first in your PATH run:
  echo 'export PATH="/usr/local/opt/expat/bin:$PATH"' >> ~/.bash_profile

For compilers to find this software you may need to set:
    LDFLAGS:  -L/usr/local/opt/expat/lib
    CPPFLAGS: -I/usr/local/opt/expat/include

==> Summary
🍺  /usr/local/Cellar/expat/2.2.2: 16 files, 398.7KB
==> Installing dependencies for gtk+: gettext, libffi, pcre, glib, jpeg, libtiff, libpng, pkg-config, freetype, fontconfig, pixman, cairo, readline, sqlite, gdbm, openssl, python, gobject-introspection, shared-mime-info, gdk-pixbuf, atk, graphite2, icu4c, harfbuzz, pango, hicolor-icon-theme
==> Installing gtk+ dependency: gettext
==> Downloading https://homebrew.bintray.com/bottles/gettext-0.19.8.1.sierra.bottle.tar.gz
==> Downloading from https://akamai.bintray.com/83/8368522242c5fe33acd5c80b5f1321559da9efe20878da6e4b9507
######################################################################## 100,0%
==> Pouring gettext-0.19.8.1.sierra.bottle.tar.gz
==> Caveats
This formula is keg-only, which means it was not symlinked into /usr/local,
because macOS provides the BSD gettext library & some software gets confused if both are in the library path.

If you need to have this software first in your PATH run:
  echo 'export PATH="/usr/local/opt/gettext/bin:$PATH"' >> ~/.bash_profile

For compilers to find this software you may need to set:
    LDFLAGS:  -L/usr/local/opt/gettext/lib
    CPPFLAGS: -I/usr/local/opt/gettext/include

==> Summary
🍺  /usr/local/Cellar/gettext/0.19.8.1: 1,934 files, 16.9MB
==> Installing gtk+ dependency: libffi
==> Downloading https://homebrew.bintray.com/bottles/libffi-3.2.1.sierra.bottle.tar.gz
######################################################################## 100,0%
==> Pouring libffi-3.2.1.sierra.bottle.tar.gz
==> Caveats
This formula is keg-only, which means it was not symlinked into /usr/local,
because some formulae require a newer version of libffi.

For compilers to find this software you may need to set:
    LDFLAGS:  -L/usr/local/opt/libffi/lib

==> Summary
🍺  /usr/local/Cellar/libffi/3.2.1: 16 files, 297.0KB
==> Installing gtk+ dependency: pcre
==> Downloading https://homebrew.bintray.com/bottles/pcre-8.41.sierra.bottle.tar.gz
==> Downloading from https://akamai.bintray.com/61/61893a4a65d393f1b4447b79550569b341ba61b49e36900a35f59207bba11923?__gda__=exp=1500324736~hmac=f8fc29e018c468d1f47aa264993344ad08b5a6510c874fd826ca7d57a4729ddf&respo
######################################################################## 100,0%
==> Pouring pcre-8.41.sierra.bottle.tar.gz
🍺  /usr/local/Cellar/pcre/8.41: 204 files, 5.3MB
==> Installing gtk+ dependency: glib
==> Downloading https://homebrew.bintray.com/bottles/glib-2.52.3.sierra.bottle.tar.gz
==> Downloading from https://akamai.bintray.com/66/6676ac794f50963131d761521b174c4efee254ed81c87bb232dc0d257c18b9a3?__gda__=exp=1500324740~hmac=4cc1e024b476086802fb247806d889241a4252091dd17f9d7cfef657cc3f8273&respo
######################################################################## 100,0%
==> Pouring glib-2.52.3.sierra.bottle.tar.gz
🍺  /usr/local/Cellar/glib/2.52.3: 430 files, 22.6MB
==> Installing gtk+ dependency: jpeg
==> Downloading https://homebrew.bintray.com/bottles/jpeg-8d.sierra.bottle.2.tar.gz
==> Downloading from https://akamai.bintray.com/85/85d1f6055de99c1b764c697498bb86d003f5d24b324133f036f0393b97b3e869?__gda__=exp=1500324752~hmac=0c1786e3de3f21eb0a6c4aa4f4d14598738594640cc6721daeae5f5d32c3890d&respo
######################################################################## 100,0%
==> Pouring jpeg-8d.sierra.bottle.2.tar.gz
🍺  /usr/local/Cellar/jpeg/8d: 19 files, 708.3KB
==> Installing gtk+ dependency: libtiff
==> Downloading https://homebrew.bintray.com/bottles/libtiff-4.0.8_1.sierra.bottle.tar.gz
==> Downloading from https://akamai.bintray.com/05/05816933252a551b69ef2999fd735a17c495790ef42b7a31d15b285209f0e22d?__gda__=exp=1500324754~hmac=232ee0ca253af292444b074beee70c31b78d096cb23e2a230c581760e834b5f0&respo
######################################################################## 100,0%
==> Pouring libtiff-4.0.8_1.sierra.bottle.tar.gz
🍺  /usr/local/Cellar/libtiff/4.0.8_1: 245 files, 3.4MB
==> Installing gtk+ dependency: libpng
==> Downloading https://homebrew.bintray.com/bottles/libpng-1.6.30.sierra.bottle.tar.gz
==> Downloading from https://akamai.bintray.com/8b/8b9d3993c9e7e7e488540d1e3d87d41ade6f3902acd6a147548b4d43818af49a?__gda__=exp=1500324757~hmac=8c98c8a51f23d9636b09089b0d250df707b7264bd1a9894b8b8620de3c3f8b4b&respo
######################################################################## 100,0%
==> Pouring libpng-1.6.30.sierra.bottle.tar.gz
🍺  /usr/local/Cellar/libpng/1.6.30: 26 files, 1.2MB
==> Installing gtk+ dependency: pkg-config
==> Downloading https://homebrew.bintray.com/bottles/pkg-config-0.29.2.sierra.bottle.tar.gz
==> Downloading from https://akamai.bintray.com/8e/8eb723bfc03cd468d779d54d015d47d2e8ab1dd4d35e595ab4abaca8833b3277?__gda__=exp=1500324759~hmac=aec48fd05379d11326576d37e068f8d74b8a0133de39a33685885af157aadf81&respo
######################################################################## 100,0%
==> Pouring pkg-config-0.29.2.sierra.bottle.tar.gz
🍺  /usr/local/Cellar/pkg-config/0.29.2: 11 files, 627KB
==> Installing gtk+ dependency: freetype
==> Downloading https://homebrew.bintray.com/bottles/freetype-2.8.sierra.bottle.tar.gz
==> Downloading from https://akamai.bintray.com/f2/f22537dd3f8b5638a712c7a6231f0b57359c4adef0557b6e90b92e11d930640f?__gda__=exp=1500324761~hmac=f51be102a9e087affefbf253ce24cfe36d6a9441cc79c5f3286b6d912ed2ff7a&respo
######################################################################## 100,0%
==> Pouring freetype-2.8.sierra.bottle.tar.gz
🍺  /usr/local/Cellar/freetype/2.8: 63 files, 2.6MB
==> Installing gtk+ dependency: fontconfig
==> Downloading https://homebrew.bintray.com/bottles/fontconfig-2.12.4.sierra.bottle.tar.gz
==> Downloading from https://akamai.bintray.com/05/05f90844fa324f510fdda497177a12ae30532368ecd7f4ead5ecd63fcd0eb66b?__gda__=exp=1500324763~hmac=0f002f0296a8c4e4d94ca42a25ac775d244555b660c6e177f970b8a3622a8788&respo
######################################################################## 100,0%
==> Pouring fontconfig-2.12.4.sierra.bottle.tar.gz
==> Regenerating font cache, this may take a while
==> /usr/local/Cellar/fontconfig/2.12.4/bin/fc-cache -frv
🍺  /usr/local/Cellar/fontconfig/2.12.4: 487 files, 3.1MB
==> Installing gtk+ dependency: pixman
==> Downloading https://homebrew.bintray.com/bottles/pixman-0.34.0_1.sierra.bottle.tar.gz
==> Downloading from https://akamai.bintray.com/52/5271f5c3bb4c524047aaa1aaafa183908b6fa8ea8c5224fd30a04c53cd6c317d?__gda__=exp=1500324837~hmac=8345cd5b0063efe9869e33328e2abec765fe681af39679fc1939f2f50e8e6798&response-content-disposi
######################################################################## 100,0%
==> Pouring pixman-0.34.0_1.sierra.bottle.tar.gz
🍺  /usr/local/Cellar/pixman/0.34.0_1: 13 files, 1.3MB
==> Installing gtk+ dependency: cairo
==> Downloading https://homebrew.bintray.com/bottles/cairo-1.14.10.sierra.bottle.tar.gz
==> Downloading from https://akamai.bintray.com/0c/0cf7f50b38512fd676b6b14f5b22961ababa3958c448f6485055bdad3a04b439?__gda__=exp=1500324840~hmac=8375242d46fbd8db0731bf13d21d09785d6234b23ab3b44ff570c137017e7fe7&response-content-disposi
######################################################################## 100,0%
==> Pouring cairo-1.14.10.sierra.bottle.tar.gz
🍺  /usr/local/Cellar/cairo/1.14.10: 118 files, 5.8MB
==> Installing gtk+ dependency: readline
==> Downloading https://homebrew.bintray.com/bottles/readline-7.0.3_1.sierra.bottle.tar.gz
==> Downloading from https://akamai.bintray.com/af/af7886c963fe3e9f58c45d679a64b278f4df7b172bbd978cf42658a7fd7b4a2a?__gda__=exp=1500324843~hmac=79fb8f2626a296e5e73d6c4adf3fb3043dc7b33551f9fdef1e0e9aa26f25511e&response-content-disposi
######################################################################## 100,0%
==> Pouring readline-7.0.3_1.sierra.bottle.tar.gz
==> Caveats
This formula is keg-only, which means it was not symlinked into /usr/local,
because macOS provides the BSD libedit library, which shadows libreadline.
In order to prevent conflicts when programs look for libreadline we are
defaulting this GNU Readline installation to keg-only..

For compilers to find this software you may need to set:
    LDFLAGS:  -L/usr/local/opt/readline/lib
    CPPFLAGS: -I/usr/local/opt/readline/include

==> Summary
🍺  /usr/local/Cellar/readline/7.0.3_1: 46 files, 1.5MB
==> Installing gtk+ dependency: sqlite
==> Downloading https://homebrew.bintray.com/bottles/sqlite-3.19.3.sierra.bottle.tar.gz
==> Downloading from https://akamai.bintray.com/19/196672a2e3e23b53f0237b200959ff665a718f2a49cc90f4731349b87c072fc9?__gda__=exp=1500324846~hmac=9e50e2604c00bc8219b8362e517847322deb51deafcfeea9d685a967d7e321cc&response-content-disposi
######################################################################## 100,0%
==> Pouring sqlite-3.19.3.sierra.bottle.tar.gz
==> Caveats
This formula is keg-only, which means it was not symlinked into /usr/local,
because macOS provides an older sqlite3.

If you need to have this software first in your PATH run:
  echo 'export PATH="/usr/local/opt/sqlite/bin:$PATH"' >> ~/.bash_profile

For compilers to find this software you may need to set:
    LDFLAGS:  -L/usr/local/opt/sqlite/lib
    CPPFLAGS: -I/usr/local/opt/sqlite/include
For pkg-config to find this software you may need to set:
    PKG_CONFIG_PATH: /usr/local/opt/sqlite/lib/pkgconfig

==> Summary
🍺  /usr/local/Cellar/sqlite/3.19.3: 12 files, 2.9MB
==> Installing gtk+ dependency: gdbm
==> Downloading https://homebrew.bintray.com/bottles/gdbm-1.13.sierra.bottle.tar.gz
######################################################################## 100,0%
==> Pouring gdbm-1.13.sierra.bottle.tar.gz
🍺  /usr/local/Cellar/gdbm/1.13: 19 files, 554.4KB
==> Installing gtk+ dependency: openssl
==> Downloading https://homebrew.bintray.com/bottles/openssl-1.0.2l.sierra.bottle.tar.gz
==> Downloading from https://akamai.bintray.com/b9/b9a6d41e2889890de8db396c2c2809711baff4272494eb4011c6473f099ba4f1?__gda__=exp=1500324850~hmac=05bfe16a8dec4d2b404fd411f7e365e24f6c7193a276a24a82a1780188cf782a&response-content-disposi
######################################################################## 100,0%
==> Pouring openssl-1.0.2l.sierra.bottle.tar.gz
==> Caveats
A CA file has been bootstrapped using certificates from the SystemRoots
keychain. To add additional certificates (e.g. the certificates added in
the System keychain), place .pem files in
  /usr/local/etc/openssl/certs

and run
  /usr/local/opt/openssl/bin/c_rehash

This formula is keg-only, which means it was not symlinked into /usr/local,
because Apple has deprecated use of OpenSSL in favor of its own TLS and crypto libraries.

If you need to have this software first in your PATH run:
  echo 'export PATH="/usr/local/opt/openssl/bin:$PATH"' >> ~/.bash_profile

For compilers to find this software you may need to set:
    LDFLAGS:  -L/usr/local/opt/openssl/lib
    CPPFLAGS: -I/usr/local/opt/openssl/include
For pkg-config to find this software you may need to set:
    PKG_CONFIG_PATH: /usr/local/opt/openssl/lib/pkgconfig

==> Summary
🍺  /usr/local/Cellar/openssl/1.0.2l: 1,709 files, 12.2MB
==> Installing gtk+ dependency: python
==> Downloading https://homebrew.bintray.com/bottles/python-2.7.13.sierra.bottle.1.tar.gz
==> Downloading from https://akamai.bintray.com/04/04406760996fadee04eecd6fae7870291e659145c590f88d85da70b0bda21df6?__gda__=exp=1500324859~hmac=d7f48f181619030d154dc5ad8cb7b623f8b43dd7cae2836a9e9e699db85b47b6&response-content-disposi
######################################################################## 100,0%
==> Pouring python-2.7.13.sierra.bottle.1.tar.gz
Error: The `brew link` step did not complete successfully
The formula built, but is not symlinked into /usr/local
Could not symlink bin/2to3
Target /usr/local/bin/2to3
already exists. You may want to remove it:
  rm '/usr/local/bin/2to3'

To force the link and overwrite all conflicting files:
  brew link --overwrite python

To list all files that would be deleted:
  brew link --overwrite --dry-run python

Possible conflicting files are:
/usr/local/bin/2to3 -> /Library/Frameworks/Python.framework/Versions/3.6/bin/2to3
==> /usr/local/Cellar/python/2.7.13/bin/python -s setup.py --no-user-cfg install --force --verbose --single-version-externally-managed --record=installed.txt --install-scripts=/usr/local/Cellar/python/2.7.13/bin --install-lib=/usr/lo
==> /usr/local/Cellar/python/2.7.13/bin/python -s setup.py --no-user-cfg install --force --verbose --single-version-externally-managed --record=installed.txt --install-scripts=/usr/local/Cellar/python/2.7.13/bin --install-lib=/usr/lo
==> /usr/local/Cellar/python/2.7.13/bin/python -s setup.py --no-user-cfg install --force --verbose --single-version-externally-managed --record=installed.txt --install-scripts=/usr/local/Cellar/python/2.7.13/bin --install-lib=/usr/lo
==> Caveats
Pip and setuptools have been installed. To update them
  pip install --upgrade pip setuptools

You can install Python packages with
  pip install <package>

They will install into the site-package directory
  /usr/local/lib/python2.7/site-packages

See: http://docs.brew.sh/Homebrew-and-Python.html
==> Summary
🍺  /usr/local/Cellar/python/2.7.13: 3,526 files, 48MB
==> Installing gtk+ dependency: gobject-introspection
==> Downloading https://homebrew.bintray.com/bottles/gobject-introspection-1.52.1.sierra.bottle.tar.gz
==> Downloading from https://akamai.bintray.com/4e/4e73519510f4e86ed98fa1238695b904530fcd5da8334486c85845d75799b050?__gda__=exp=1500324880~hmac=23d1f2bdbe70ac79ca3df5ee9b368169fabf5c09db92206f4ef40630a6a84169&response-content-disposi
######################################################################## 100,0%
==> Pouring gobject-introspection-1.52.1.sierra.bottle.tar.gz
🍺  /usr/local/Cellar/gobject-introspection/1.52.1: 172 files, 9.7MB
==> Installing gtk+ dependency: shared-mime-info
==> Downloading https://homebrew.bintray.com/bottles/shared-mime-info-1.8_1.sierra.bottle.tar.gz
==> Downloading from https://akamai.bintray.com/06/06cca38ff0a8777b3897caaafdbf701d3db751e21e5b0f2dacc0296bfebbfca9?__gda__=exp=1500324884~hmac=466d426e8f25ae1a5b5def08d160ed68c31f749c562a36171d3472faf0f01a0e&response-content-disposi
######################################################################## 100,0%
==> Pouring shared-mime-info-1.8_1.sierra.bottle.tar.gz
==> /usr/local/Cellar/shared-mime-info/1.8_1/bin/update-mime-database /usr/local/share/mime
🍺  /usr/local/Cellar/shared-mime-info/1.8_1: 83 files, 4.4MB
==> Installing gtk+ dependency: gdk-pixbuf
==> Downloading https://homebrew.bintray.com/bottles/gdk-pixbuf-2.36.6.sierra.bottle.1.tar.gz
==> Downloading from https://akamai.bintray.com/37/3773ef77ffe5fed4c613fcaa071b0ba0b956d6a65b0018d5589220fd56a42bbc?__gda__=exp=1500324888~hmac=b60b892701133d5cd90a3e2d89028ceec2ee9e93f9cdaaf88ba8989ed8ed8176&response-content-disposi
######################################################################## 100,0%
==> Pouring gdk-pixbuf-2.36.6.sierra.bottle.1.tar.gz
==> /usr/local/Cellar/gdk-pixbuf/2.36.6/bin/gdk-pixbuf-query-loaders --update-cache
🍺  /usr/local/Cellar/gdk-pixbuf/2.36.6: 200 files, 4.3MB
==> Installing gtk+ dependency: atk
==> Downloading https://homebrew.bintray.com/bottles/atk-2.24.0.sierra.bottle.tar.gz
==> Downloading from https://akamai.bintray.com/89/89d59856b8bbd0a51961c0569237da2f6119fddd40f67b50d96651483fe9be10?__gda__=exp=1500324893~hmac=7280fbb42767b84ec86981f1a40450333ebfd9f8cf272a8fbfbc0339fc139a79&response-content-disposi
######################################################################## 100,0%
==> Pouring atk-2.24.0.sierra.bottle.tar.gz
🍺  /usr/local/Cellar/atk/2.24.0: 209 files, 3.3MB
==> Installing gtk+ dependency: graphite2
==> Downloading https://homebrew.bintray.com/bottles/graphite2-1.3.10.sierra.bottle.tar.gz
######################################################################## 100,0%
==> Pouring graphite2-1.3.10.sierra.bottle.tar.gz
🍺  /usr/local/Cellar/graphite2/1.3.10: 18 files, 259.3KB
==> Installing gtk+ dependency: icu4c
==> Downloading https://homebrew.bintray.com/bottles/icu4c-58.2.sierra.bottle.tar.gz
==> Downloading from https://akamai.bintray.com/77/779eda1c03f44b54300b5e70143f6bd4866b6f5f582e4216124649539164b029?__gda__=exp=1500324899~hmac=81cfcbe5338b5e0727975c22d84a35786f90c182f5f77febde91bd1a797af5bb&response-content-disposi
######################################################################## 100,0%
==> Pouring icu4c-58.2.sierra.bottle.tar.gz
==> Caveats
This formula is keg-only, which means it was not symlinked into /usr/local,
because macOS provides libicucore.dylib (but nothing else).

If you need to have this software first in your PATH run:
  echo 'export PATH="/usr/local/opt/icu4c/bin:$PATH"' >> ~/.bash_profile
  echo 'export PATH="/usr/local/opt/icu4c/sbin:$PATH"' >> ~/.bash_profile

For compilers to find this software you may need to set:
    LDFLAGS:  -L/usr/local/opt/icu4c/lib
    CPPFLAGS: -I/usr/local/opt/icu4c/include
For pkg-config to find this software you may need to set:
    PKG_CONFIG_PATH: /usr/local/opt/icu4c/lib/pkgconfig

==> Summary
🍺  /usr/local/Cellar/icu4c/58.2: 242 files, 65MB
==> Installing gtk+ dependency: harfbuzz
==> Downloading https://homebrew.bintray.com/bottles/harfbuzz-1.4.6_1.sierra.bottle.tar.gz
==> Downloading from https://akamai.bintray.com/4c/4c81e30eec38ace35bc49f3c8c42cefc5c68a3ba8235f583e0a3d7ba81c79023?__gda__=exp=1500324925~hmac=6615722a4a95d1110d2b6d90f5303a03e1fea1845c19d45c16016f43ea406fe8&response-content-disposi
######################################################################## 100,0%
==> Pouring harfbuzz-1.4.6_1.sierra.bottle.tar.gz
🍺  /usr/local/Cellar/harfbuzz/1.4.6_1: 134 files, 5.3MB
==> Installing gtk+ dependency: pango
==> Downloading https://homebrew.bintray.com/bottles/pango-1.40.6.sierra.bottle.tar.gz
==> Downloading from https://akamai.bintray.com/9a/9a3b7c067180b377e5caac5debdb477feda07db598602d34c9e037b6c4701402?__gda__=exp=1500324930~hmac=0db87cf5461f1bf0dc20bd9a435a9463e5a581f4c10161627642c184a5353ed0&response-content-disposi
######################################################################## 100,0%
==> Pouring pango-1.40.6.sierra.bottle.tar.gz
🍺  /usr/local/Cellar/pango/1.40.6: 105 files, 4.4MB
==> Installing gtk+ dependency: hicolor-icon-theme
==> Downloading https://homebrew.bintray.com/bottles/hicolor-icon-theme-0.15.sierra.bottle.tar.gz
######################################################################## 100,0%
==> Pouring hicolor-icon-theme-0.15.sierra.bottle.tar.gz
🍺  /usr/local/Cellar/hicolor-icon-theme/0.15: 6 files, 48.5KB
==> Installing gtk+
==> Downloading https://homebrew.bintray.com/bottles/gtk+-2.24.31_1.sierra.bottle.tar.gz
==> Downloading from https://akamai.bintray.com/86/860a8dd62ae8990a7dc3c403421fa3ee6bdf8ae810463fd5368094676b7c827d?__gda__=exp=1500324934~hmac=c9ac56a7f9e90d01505f550b72c4ee083cdb5d5d50189afece20a555b1cc7a11&response-content-disposi
######################################################################## 100,0%
==> Pouring gtk+-2.24.31_1.sierra.bottle.tar.gz
🍺  /usr/local/Cellar/gtk+/2.24.31_1: 1,199 files, 53.0MB
==> Installing dependencies for gtksourceview: xz, python3, libepoxy, gsettings-desktop-schemas, gtk+3, pygobject, py2cairo, pygtk, gtk-mac-integration
==> Installing gtksourceview dependency: xz
==> Downloading https://homebrew.bintray.com/bottles/xz-5.2.3.sierra.bottle.tar.gz
==> Downloading from https://akamai.bintray.com/25/2518e5105c2b290755cda0fd5cd7f71eea4cd4741b70c48250eed1750c3a6814?__gda__=exp=1500324966~hmac=a478ddf24ef47771e263972a7e0bbd921855902ae476366de4bc485523a72198&response-content-disposi
######################################################################## 100,0%
==> Pouring xz-5.2.3.sierra.bottle.tar.gz
🍺  /usr/local/Cellar/xz/5.2.3: 92 files, 1.4MB
==> Installing gtksourceview dependency: python3
==> Downloading https://homebrew.bintray.com/bottles/python3-3.6.2.sierra.bottle.tar.gz
==> Downloading from https://akamai.bintray.com/a0/a0cde735f5c8e959d09ef9077dc18be2f84db8ec0bdccf99828d991c0f24688f?__gda__=exp=1500324969~hmac=c8e522e7375fb6226821749fe6305079f25bb1abfa069b2887652f1c9d4234a9&response-content-disposi
######################################################################## 100,0%
==> Pouring python3-3.6.2.sierra.bottle.tar.gz
Error: The `brew link` step did not complete successfully
The formula built, but is not symlinked into /usr/local
Could not symlink bin/2to3-3.6
Target /usr/local/bin/2to3-3.6
already exists. You may want to remove it:
  rm '/usr/local/bin/2to3-3.6'

To force the link and overwrite all conflicting files:
  brew link --overwrite python3

To list all files that would be deleted:
  brew link --overwrite --dry-run python3

Possible conflicting files are:
/usr/local/bin/2to3-3.6 -> /Library/Frameworks/Python.framework/Versions/3.6/bin/2to3-3.6
/usr/local/bin/idle3 -> /Library/Frameworks/Python.framework/Versions/3.6/bin/idle3
/usr/local/bin/idle3.6 -> /Library/Frameworks/Python.framework/Versions/3.6/bin/idle3.6
/usr/local/bin/pydoc3 -> /Library/Frameworks/Python.framework/Versions/3.6/bin/pydoc3
/usr/local/bin/pydoc3.6 -> /Library/Frameworks/Python.framework/Versions/3.6/bin/pydoc3.6
/usr/local/bin/python3 -> /Library/Frameworks/Python.framework/Versions/3.6/bin/python3
/usr/local/bin/python3-config -> /Library/Frameworks/Python.framework/Versions/3.6/bin/python3-config
/usr/local/bin/python3.6 -> /Library/Frameworks/Python.framework/Versions/3.6/bin/python3.6
/usr/local/bin/python3.6-config -> /Library/Frameworks/Python.framework/Versions/3.6/bin/python3.6-config
/usr/local/bin/python3.6m -> /Library/Frameworks/Python.framework/Versions/3.6/bin/python3.6m
/usr/local/bin/python3.6m-config -> /Library/Frameworks/Python.framework/Versions/3.6/bin/python3.6m-config
/usr/local/bin/pyvenv -> /Library/Frameworks/Python.framework/Versions/3.6/bin/pyvenv
/usr/local/bin/pyvenv-3.6 -> /Library/Frameworks/Python.framework/Versions/3.6/bin/pyvenv-3.6
==> /usr/local/Cellar/python3/3.6.2/bin/python3 -s setup.py --no-user-cfg install --force --verbose --install-scripts=/usr/local/Cellar/python3/3.6.2/bin --install-lib=/usr/local/lib/python3.6/site-packages --single-version-externall
==> /usr/local/Cellar/python3/3.6.2/bin/python3 -s setup.py --no-user-cfg install --force --verbose --install-scripts=/usr/local/Cellar/python3/3.6.2/bin --install-lib=/usr/local/lib/python3.6/site-packages --single-version-externall
==> /usr/local/Cellar/python3/3.6.2/bin/python3 -s setup.py --no-user-cfg install --force --verbose --install-scripts=/usr/local/Cellar/python3/3.6.2/bin --install-lib=/usr/local/lib/python3.6/site-packages --single-version-externall
==> Caveats
Pip, setuptools, and wheel have been installed. To update them
  pip3 install --upgrade pip setuptools wheel

You can install Python packages with
  pip3 install <package>

They will install into the site-package directory
  /usr/local/lib/python3.6/site-packages

See: http://docs.brew.sh/Homebrew-and-Python.html
==> Summary
🍺  /usr/local/Cellar/python3/3.6.2: 3,598 files, 55.9MB
==> Installing gtksourceview dependency: libepoxy
==> Downloading https://homebrew.bintray.com/bottles/libepoxy-1.4.3.sierra.bottle.tar.gz
==> Downloading from https://akamai.bintray.com/a9/a96a0e088b6f292422108da73868700ef1a332ebd170695a77e90be7a12a4f86?__gda__=exp=1500324991~hmac=1740c1bfdc14958c35a266dc8e0e45b2cd5a4f124379099fbed587ef69cf35a5&response-content-disposi
######################################################################## 100,0%
==> Pouring libepoxy-1.4.3.sierra.bottle.tar.gz
🍺  /usr/local/Cellar/libepoxy/1.4.3: 11 files, 3.2MB
==> Installing gtksourceview dependency: gsettings-desktop-schemas
==> Downloading https://homebrew.bintray.com/bottles/gsettings-desktop-schemas-3.24.0.sierra.bottle.tar.gz
==> Downloading from https://akamai.bintray.com/b8/b8a7f888ffff66f3f5806659a1bd0e91517ab95a12c439d0ec9551067e41ae72?__gda__=exp=1500324994~hmac=b602d51dfc5c9c56e489564da03109ccf562a28c143c705616f563a861230502&response-content-disposi
######################################################################## 100,0%
==> Pouring gsettings-desktop-schemas-3.24.0.sierra.bottle.tar.gz
==> /usr/local/opt/glib/bin/glib-compile-schemas /usr/local/share/glib-2.0/schemas
🍺  /usr/local/Cellar/gsettings-desktop-schemas/3.24.0: 93 files, 3.7MB
==> Installing gtksourceview dependency: gtk+3
==> Downloading https://homebrew.bintray.com/bottles/gtk+3-3.22.16.sierra.bottle.tar.gz
==> Downloading from https://akamai.bintray.com/a9/a9306c76f8ec710028f16b2decedc7265e1e9fbf95c25a0466d9bd9024380676?__gda__=exp=1500325000~hmac=f500e46c8ef8a422325431b64aa67dd91c06108d4302624b7cd9bf4fbbbdaec8&response-content-disposi
######################################################################## 100,0%
==> Pouring gtk+3-3.22.16.sierra.bottle.tar.gz
==> /usr/local/opt/glib/bin/glib-compile-schemas /usr/local/share/glib-2.0/schemas
🍺  /usr/local/Cellar/gtk+3/3.22.16: 1,370 files, 68.8MB
==> Installing gtksourceview dependency: pygobject
==> Downloading https://homebrew.bintray.com/bottles/pygobject-2.28.6_1.sierra.bottle.tar.gz
==> Downloading from https://akamai.bintray.com/9a/9a10d979f637cfc9abc46839fa470672ee97a33be5f8ea9a8b725d44f60ed0ba?__gda__=exp=1500325028~hmac=a0b9ee8d4828d5565e71336c5feec517d7d387bffc41c9d09cc680f48468f6a5&response-content-disposi
######################################################################## 100,0%
==> Pouring pygobject-2.28.6_1.sierra.bottle.tar.gz
==> Caveats
Python modules have been installed and Homebrew's site-packages is not
in your Python sys.path, so you will not be able to import the modules
this formula installed. If you plan to develop with these modules,
please run:
  mkdir -p /Users/***************/Library/Python/2.7/lib/python/site-packages
  echo 'import site; site.addsitedir("/usr/local/lib/python2.7/site-packages")' >> /Users/***************/Library/Python/2.7/lib/python/site-packages/homebrew.pth
==> Summary
🍺  /usr/local/Cellar/pygobject/2.28.6_1: 139 files, 3.2MB
==> Installing gtksourceview dependency: py2cairo
==> Downloading https://homebrew.bintray.com/bottles/py2cairo-1.10.0_1.sierra.bottle.tar.gz
######################################################################## 100,0%
==> Pouring py2cairo-1.10.0_1.sierra.bottle.tar.gz
==> Caveats
Python modules have been installed and Homebrew's site-packages is not
in your Python sys.path, so you will not be able to import the modules
this formula installed. If you plan to develop with these modules,
please run:
  mkdir -p /Users/***************/Library/Python/2.7/lib/python/site-packages
  echo 'import site; site.addsitedir("/usr/local/lib/python2.7/site-packages")' >> /Users/***************/Library/Python/2.7/lib/python/site-packages/homebrew.pth
==> Summary
🍺  /usr/local/Cellar/py2cairo/1.10.0_1: 9 files, 116.5KB
==> Installing gtksourceview dependency: pygtk
==> Downloading https://homebrew.bintray.com/bottles/pygtk-2.24.0_1.sierra.bottle.2.tar.gz
==> Downloading from https://akamai.bintray.com/89/89f5d6762155b369dae255ba2b3952cc09f43f899585ff8694370b6b151ca97e?__gda__=exp=1500325039~hmac=441c66e7267a6a47c6b391026b72f70eebcc4c34a0d0d838a26e973e6846de2b&response-content-disposi
######################################################################## 100,0%
==> Pouring pygtk-2.24.0_1.sierra.bottle.2.tar.gz
==> Caveats
Python modules have been installed and Homebrew's site-packages is not
in your Python sys.path, so you will not be able to import the modules
this formula installed. If you plan to develop with these modules,
please run:
  mkdir -p /Users/***************/Library/Python/2.7/lib/python/site-packages
  echo 'import site; site.addsitedir("/usr/local/lib/python2.7/site-packages")' >> /Users/***************/Library/Python/2.7/lib/python/site-packages/homebrew.pth
==> Summary
🍺  /usr/local/Cellar/pygtk/2.24.0_1: 590 files, 15.4MB
==> Installing gtksourceview dependency: gtk-mac-integration
==> Downloading https://homebrew.bintray.com/bottles/gtk-mac-integration-2.0.8_1.sierra.bottle.tar.gz
######################################################################## 100,0%
==> Pouring gtk-mac-integration-2.0.8_1.sierra.bottle.tar.gz
==> Caveats
Python modules have been installed and Homebrew's site-packages is not
in your Python sys.path, so you will not be able to import the modules
this formula installed. If you plan to develop with these modules,
please run:
  mkdir -p /Users/***************/Library/Python/2.7/lib/python/site-packages
  echo 'import site; site.addsitedir("/usr/local/lib/python2.7/site-packages")' >> /Users/***************/Library/Python/2.7/lib/python/site-packages/homebrew.pth
==> Summary
🍺  /usr/local/Cellar/gtk-mac-integration/2.0.8_1: 53 files, 343.4KB
==> Installing gtksourceview
==> Downloading https://homebrew.bintray.com/bottles/gtksourceview-2.10.5_2.sierra.bottle.tar.gz
==> Downloading from https://akamai.bintray.com/3f/3fb2f8fa75fa387446d26fff33efda69464097236347a18624a5dde92f6d73a1?__gda__=exp=1500325059~hmac=3a5e68f9fe3352ea65d72162f01c3f6a434b2fb2f471538f4da663067d3064f6&response-content-disposi
######################################################################## 100,0%
==> Pouring gtksourceview-2.10.5_2.sierra.bottle.tar.gz
🍺  /usr/local/Cellar/gtksourceview/2.10.5_2: 230 files, 4.6MB
==> Downloading https://homebrew.bintray.com/bottles/libxml2-2.9.4_3.sierra.bottle.tar.gz
==> Downloading from https://akamai.bintray.com/fb/fb8338703ee9691cc48ca8898a16baa3b2657635ebacb6071dee49725bd052d6?__gda__=exp=1500325064~hmac=a792304338544a88478da6a412996b31a4b9fdbacbb6b20a41a27057ae4ab951&response-content-disposi
######################################################################## 100,0%
==> Pouring libxml2-2.9.4_3.sierra.bottle.tar.gz
==> Caveats
This formula is keg-only, which means it was not symlinked into /usr/local,
because macOS already provides this software and installing another version in
parallel can cause all kinds of trouble.

If you need to have this software first in your PATH run:
  echo 'export PATH="/usr/local/opt/libxml2/bin:$PATH"' >> ~/.bash_profile

For compilers to find this software you may need to set:
    LDFLAGS:  -L/usr/local/opt/libxml2/lib
    CPPFLAGS: -I/usr/local/opt/libxml2/include
For pkg-config to find this software you may need to set:
    PKG_CONFIG_PATH: /usr/local/opt/libxml2/lib/pkgconfig


If you need Python to find bindings for this keg-only formula, run:
  echo /usr/local/opt/libxml2/lib/python2.7/site-packages >> /usr/local/lib/python2.7/site-packages/libxml2.pth
  mkdir -p /Users/***************/Library/Python/2.7/lib/python/site-packages
  echo 'import site; site.addsitedir("/usr/local/lib/python2.7/site-packages")' >> /Users/***************/Library/Python/2.7/lib/python/site-packages/homebrew.pth
==> Summary
🍺  /usr/local/Cellar/libxml2/2.9.4_3: 281 files, 10.4MB
OS package installation failed
***************:~ ***************$ 
***************:~ ***************$ 

















Last login: Mon Jul 17 22:39:18 on ttys002
***************:~ ***************$ opam install ocaml-top
The following actions will be performed:
  ∗  install conf-gtksourceview 2             [required by ocaml-top]
  ∗  install lablgtk            2.18.5        [required by ocaml-top]
  ∗  install ocaml-top          1.1.4 
===== ∗  3 =====
Do you want to continue ? [Y/n] y

=-=- Gathering sources =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  🐫 
[lablgtk] Archive in cache
[ocaml-top] Archive in cache

=-=- Processing actions -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  🐫 
∗  installed conf-gtksourceview.2

∗  installed lablgtk.2.18.5
∗  installed ocaml-top.1.1.4
Done.
***************:~ ***************$ 
***************:~ ***************$ 


Here the result
